/*****************************************************************************
* Model: WallFollower.qm
* File:  Src/system.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${Src::system.c} .........................................................*/
#include "system.h"
#include "stm32f4xx_hal.h"
#include "usart.h"
#include "string.h"


#if ((QP_VERSION < 580) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8)))
#error qpc version 5.8.0 or higher required
#endif

/*${AOs::System} ...........................................................*/
/*${AOs::System::ctor} .....................................................*/
void System_ctor(System* me) {
    QActive_ctor(&me->super, Q_STATE_CAST(&System_initial));
    QTimeEvt_ctorX(&me->LEDToggleEvt, &me->super, LED_TOGGLE_SIG, 0U);
}
/*${AOs::System::SM} .......................................................*/
QState System_initial(System * const me, QEvt const * const e) {
    /* ${AOs::System::SM::initial} */
    HAL_UART_Transmit(&huart2, (uint8_t*)"System Startup", strlen("System Startup"), HAL_MAX_DELAY);
    QTimeEvt_armX(&me->LEDToggleEvt, 500, 500);
    return Q_TRAN(&System_Active);
}
/*${AOs::System::SM::Active} ...............................................*/
QState System_Active(System * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${AOs::System::SM::Active::LED_TOGGLE} */
        case LED_TOGGLE_SIG: {
            HAL_GPIO_TogglePin(LD2_GPIO_Port, LD2_Pin);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

