/*****************************************************************************
* Model: WallFollower.qm
* File:  Inc/signals.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${Inc::signals.h} ........................................................*/
#ifndef SIGNALS_H
#define SIGNALS_H

#include "qpc.h"

enum Signals
{
    LED_TOGGLE_SIG = Q_USER_SIG,
    MAX_SIG
};

#endif
